import { readFileSync, writeFileSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
// Define the root directory for your schema files
const schemaDir = path.join(__dirname, "prisma/models");
// Get all the .prisma files in the models directory
const files = [
    "School.prisma",
    "Subscription.prisma",
    "Role.prisma",
    "User.prisma",
    "BiometricLog.prisma",
    "MoodLog.prisma",
    "Alert.prisma",
    "ParentStudentRelationship.prisma",
    "Consent.prisma",
];
// Combine the content of all files
let mergedSchema = `
// This file is auto-generated by the merge-schema.ts script. Do not edit directly.

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

`;
for (const file of files) {
    const filePath = path.join(schemaDir, file);
    const content = readFileSync(filePath, "utf-8");
    mergedSchema += `\n${content}\n`;
}
// Write the combined content to schema.prisma
writeFileSync(path.join(__dirname, "prisma/schema.prisma"), mergedSchema);
console.log("Successfully merged Prisma schema files into prisma/schema.prisma!");
//# sourceMappingURL=merge-schema.js.map